apiVersion: v1
kind: Pod
metadata:
  name: webapppod
  labels:
    component: web
spec:
  containers:
  - name: aritra
    image: arig23498/inframind
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 9090
