apiVersion: v1
kind: Service
metadata:
  name: webappnodeport
spec:
  # Make the service externally visible via the node
  type: NodePort 
  selector:
    component: web
  ports:
  - port: 9090
    targetPort: 9090
    nodePort: 30000
