apiVersion: v1
kind: Service
metadata:
  name: webapp
spec:
  type: NodePort
  ports:
  - name: webapp
    port: 9090
    protocol: TCP
    targetPort: 9090
    nodePort: 32607
  selector:
    app: myapp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webappdeploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: webapp
        image: arig23498/inframind
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 9090
